version: "3.8"

services:
  hide-and-ride:
    build: .
    ports:
      - "2221:22"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M